### ISSUE TITLE
error on load with 1.9.2 prevents factorio from loading with mod enabled.

### ISSUE THREAD

**Issue by DaveInTexas** [TheSAguy/Bio_Industries#5]
![bio-industries-1-92](https://user-images.githubusercontent.com/8439723/30100363-3a72f68c-92ae-11e7-827b-5ec77e29ea86.png)

missing file/incorrect path for the bio cannon shadow apparently

**Comment by TheSAguy** [comment]
Oops, forgot to update graphics path on copied code...
Should be fixed in 1.9.3
